//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSMessenger
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public byte SourceCompanyID { get; set; }
        public short SourceUserID { get; set; }
        public byte DestinationCompanyID { get; set; }
        public short DestinationUserID { get; set; }
        public string Text { get; set; }
        public System.DateTime SentDateTime { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.TimeSpan> ReceivedTime { get; set; }
        public Nullable<System.DateTime> ReadedDateTime { get; set; }
    
        public virtual User SourceUser { get; set; }
        public virtual User DestinationUser { get; set; }
    }
}
