//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSMessenger
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public byte SourceCompanyID { get; set; }
        public short SourceUserID { get; set; }
        public byte DestinationCompanyID { get; set; }
        public short DestinationUserID { get; set; }
        public int Semaphore { get; set; }
    
        public virtual User DestinationUser { get; set; }
        public virtual User SourceUser { get; set; }
    }
}
